[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'python -m pip install -r requirements-railway.txt']

[start]
cmd = 'python run.py --api-port $PORT'
